
-- geo position
INSERT INTO public.geo_position (id, latitude, longitude, country_code, state_code, city_id, region_common, region_dvd, region_xbox360, region_xboxone, region_playstation3, region_playstation4, region_nintendo, created_date) VALUES (1, 55.108, 54.039, 'USA', null, 1, 0, 0, 0, 0, 0, 0, 0, '2018-05-22 13:17:42.947280');

-- vpn server
INSERT INTO public.vpnserver (uuid, version, state_version, type_id, status_id, bandwidth, load, geo_position_id, created_date) VALUES ('c872e7f0-76d6-4a4e-826e-c56a7c05958a', 1, 1, 1, 1, 0, 0, 1, '2018-05-22 13:18:14.041628');

-- vpn server configuration
INSERT INTO public.vpnserver_configuration (uuid, user_uuid, server_uuid, file_path, created_date) VALUES ('8f525324-f752-4135-bab7-38e0f1ff96f9', 'c872e7f0-76d6-4a4e-826e-c56a7c05958a', 'c872e7f0-76d6-4a4e-826e-c56a7c05958a', '/file/path', '2018-05-22 13:25:29.392613');

-- NSI

-- vpn server statuses
INSERT INTO public.vpnserver_status(id, code, description) VALUES(0, 'unknown', 'Unknown, for reports only');
INSERT INTO public.vpnserver_status(id, code, description) VALUES(1, 'op', 'Operational');
INSERT INTO public.vpnserver_status(id, code, description) VALUES(2, 'removed', 'Removed of service');
INSERT INTO public.vpnserver_status(id, code, description) VALUES(3, 'maintenance', 'Under Maintenance');
INSERT INTO public.vpnserver_status(id, code, description) VALUES(4, 'op_nnc', 'Operational. No new connections available, preparing for Maintenance');
INSERT INTO public.vpnserver_status(id, code, description) VALUES(5, 'op_test', 'Operational; test mode');
INSERT INTO public.vpnserver_status(id, code, description) VALUES(6, 'removed_test', 'Removed of service; test mode');
INSERT INTO public.vpnserver_status(id, code, description) VALUES(7, 'maintenance_test', 'Under Maintenance; test mode');
INSERT INTO public.vpnserver_status(id, code, description) VALUES(8, 'op_nnc_test', 'Operational. No new connections available, preparing for Maintenance; test mode');

-- vpn types
INSERT INTO public.vpn_type (id, code, description) VALUES (0, 'unknown', 'Unknown, for reports only');
INSERT INTO public.vpn_type (id, code, description) VALUES (1, 'openvpn', 'Standard OpenVPN server');
INSERT INTO public.vpn_type (id, code, description) VALUES (2, 'ikev2', 'IPSec w IKEv2');


INSERT INTO public.country(name, code) VALUES ('Afghanistan', 'AFG');
INSERT INTO public.country(name, code) VALUES ('ALA	Aland Islands', 'ALA');
INSERT INTO public.country(name, code) VALUES ('Albania', 'ALB');
INSERT INTO public.country(name, code) VALUES ('Algeria', 'DZA');
INSERT INTO public.country(name, code) VALUES ('American Samoa', 'ASM');
INSERT INTO public.country(name, code) VALUES ('Andorra', 'AND');
INSERT INTO public.country(name, code) VALUES ('Angola', 'AGO');
INSERT INTO public.country(name, code) VALUES ('Anguilla', 'AIA');
INSERT INTO public.country(name, code) VALUES ('Antarctica', 'ATA');
INSERT INTO public.country(name, code) VALUES ('Antigua and Barbuda', 'ATG');
INSERT INTO public.country(name, code) VALUES ('Argentina', 'ARG');
INSERT INTO public.country(name, code) VALUES ('Armenia', 'ARM');
INSERT INTO public.country(name, code) VALUES ('Aruba', 'ABW');
INSERT INTO public.country(name, code) VALUES ('Australia', 'AUS');
INSERT INTO public.country(name, code) VALUES ('Austria', 'AUT');
INSERT INTO public.country(name, code) VALUES ('Azerbaijan', 'AZE');
INSERT INTO public.country(name, code) VALUES ('Bahamas', 'BHS');
INSERT INTO public.country(name, code) VALUES ('Bahrain', 'BHR');
INSERT INTO public.country(name, code) VALUES ('Bangladesh', 'BGD');
INSERT INTO public.country(name, code) VALUES ('Barbados', 'BRB');
INSERT INTO public.country(name, code) VALUES ('Belarus', 'BLR');
INSERT INTO public.country(name, code) VALUES ('Belgium', 'BEL');
INSERT INTO public.country(name, code) VALUES ('Belize', 'BLZ');
INSERT INTO public.country(name, code) VALUES ('Benin', 'BEN');
INSERT INTO public.country(name, code) VALUES ('Bermuda', 'BMU');
INSERT INTO public.country(name, code) VALUES ('Bhutan', 'BTN');
INSERT INTO public.country(name, code) VALUES ('Bolivia', 'BOL');
INSERT INTO public.country(name, code) VALUES ('Bosnia and Herzegovina', 'BIH');
INSERT INTO public.country(name, code) VALUES ('Botswana', 'BWA');
INSERT INTO public.country(name, code) VALUES ('Bouvet Island', 'BVT');
INSERT INTO public.country(name, code) VALUES ('Brazil', 'BRA');
INSERT INTO public.country(name, code) VALUES ('British Virgin Islands', 'VGB');
INSERT INTO public.country(name, code) VALUES ('British Indian Ocean Territory', 'IOT');
INSERT INTO public.country(name, code) VALUES ('Brunei Darussalam', 'BRN');
INSERT INTO public.country(name, code) VALUES ('Bulgaria', 'BGR');
INSERT INTO public.country(name, code) VALUES ('Burkina Faso', 'BFA');
INSERT INTO public.country(name, code) VALUES ('Burundi', 'BDI');
INSERT INTO public.country(name, code) VALUES ('Cambodia', 'KHM');
INSERT INTO public.country(name, code) VALUES ('Cameroon', 'CMR');
INSERT INTO public.country(name, code) VALUES ('Canada', 'CAN');
INSERT INTO public.country(name, code) VALUES ('Cape Verde', 'CPV');
INSERT INTO public.country(name, code) VALUES ('Cayman Islands', 'CYM');
INSERT INTO public.country(name, code) VALUES ('Central African Republic', 'CAF');
INSERT INTO public.country(name, code) VALUES ('Chad', 'TCD');
INSERT INTO public.country(name, code) VALUES ('Chile', 'CHL');
INSERT INTO public.country(name, code) VALUES ('China', 'CHN');
INSERT INTO public.country(name, code) VALUES ('Hong Kong, SAR China', 'HKG');
INSERT INTO public.country(name, code) VALUES ('Macao, SAR China', 'MAC');
INSERT INTO public.country(name, code) VALUES ('Christmas Island', 'CXR');
INSERT INTO public.country(name, code) VALUES ('Cocos (Keeling) Islands', 'CCK');
INSERT INTO public.country(name, code) VALUES ('Colombia', 'COL');
INSERT INTO public.country(name, code) VALUES ('Comoros', 'COM');
INSERT INTO public.country(name, code) VALUES ('Congo (Brazzaville)', 'COG');
INSERT INTO public.country(name, code) VALUES ('Congo, (Kinshasa)', 'COD');
INSERT INTO public.country(name, code) VALUES ('Cook Islands', 'COK');
INSERT INTO public.country(name, code) VALUES ('Costa Rica', 'CRI');
INSERT INTO public.country(name, code) VALUES ('Côte dIvoire', 'CIV');
INSERT INTO public.country(name, code) VALUES ('Croatia', 'HRV');
INSERT INTO public.country(name, code) VALUES ('Cuba', 'CUB');
INSERT INTO public.country(name, code) VALUES ('Cyprus', 'CYP');
INSERT INTO public.country(name, code) VALUES ('Czech Republic', 'CZE');
INSERT INTO public.country(name, code) VALUES ('Denmark', 'DNK');
INSERT INTO public.country(name, code) VALUES ('Djibouti', 'DJI');
INSERT INTO public.country(name, code) VALUES ('Dominica', 'DMA');
INSERT INTO public.country(name, code) VALUES ('Dominican Republic', 'DOM');
INSERT INTO public.country(name, code) VALUES ('Ecuador', 'ECU');
INSERT INTO public.country(name, code) VALUES ('Egypt', 'EGY');
INSERT INTO public.country(name, code) VALUES ('El Salvador', 'SLV');
INSERT INTO public.country(name, code) VALUES ('Equatorial Guinea', 'GNQ');
INSERT INTO public.country(name, code) VALUES ('Eritrea', 'ERI');
INSERT INTO public.country(name, code) VALUES ('Estonia', 'EST');
INSERT INTO public.country(name, code) VALUES ('Ethiopia', 'ETH');
INSERT INTO public.country(name, code) VALUES ('Falkland Islands (Malvinas)', 'FLK');
INSERT INTO public.country(name, code) VALUES ('Faroe Islands', 'FRO');
INSERT INTO public.country(name, code) VALUES ('Fiji', 'FJI');
INSERT INTO public.country(name, code) VALUES ('Finland', 'FIN');
INSERT INTO public.country(name, code) VALUES ('France', 'FRA');
INSERT INTO public.country(name, code) VALUES ('French Guiana', 'GUF');
INSERT INTO public.country(name, code) VALUES ('French Polynesia', 'PYF');
INSERT INTO public.country(name, code) VALUES ('French Southern Territories', 'ATF');
INSERT INTO public.country(name, code) VALUES ('Gabon', 'GAB');
INSERT INTO public.country(name, code) VALUES ('Gambia', 'GMB');
INSERT INTO public.country(name, code) VALUES ('Georgia', 'GEO');
INSERT INTO public.country(name, code) VALUES ('Germany', 'DEU');
INSERT INTO public.country(name, code) VALUES ('Ghana', 'GHA');
INSERT INTO public.country(name, code) VALUES ('Gibraltar', 'GIB');
INSERT INTO public.country(name, code) VALUES ('Greece', 'GRC');
INSERT INTO public.country(name, code) VALUES ('Greenland', 'GRL');
INSERT INTO public.country(name, code) VALUES ('Grenada', 'GRD');
INSERT INTO public.country(name, code) VALUES ('Guadeloupe', 'GLP');
INSERT INTO public.country(name, code) VALUES ('Guam', 'GUM');
INSERT INTO public.country(name, code) VALUES ('Guatemala', 'GTM');
INSERT INTO public.country(name, code) VALUES ('Guernsey', 'GGY');
INSERT INTO public.country(name, code) VALUES ('Guinea', 'GIN');
INSERT INTO public.country(name, code) VALUES ('Guinea-Bissau', 'GNB');
INSERT INTO public.country(name, code) VALUES ('Guyana', 'GUY');
INSERT INTO public.country(name, code) VALUES ('Haiti', 'HTI');
INSERT INTO public.country(name, code) VALUES ('Heard and Mcdonald Islands', 'HMD');
INSERT INTO public.country(name, code) VALUES ('Holy See (Vatican City State)', 'VAT');
INSERT INTO public.country(name, code) VALUES ('Honduras', 'HND');
INSERT INTO public.country(name, code) VALUES ('Hungary', 'HUN');
INSERT INTO public.country(name, code) VALUES ('Iceland', 'ISL');
INSERT INTO public.country(name, code) VALUES ('India', 'IND');
INSERT INTO public.country(name, code) VALUES ('Indonesia', 'IDN');
INSERT INTO public.country(name, code) VALUES ('Iran, Islamic Republic of', 'IRN');
INSERT INTO public.country(name, code) VALUES ('Iraq', 'IRQ');
INSERT INTO public.country(name, code) VALUES ('Ireland', 'IRL');
INSERT INTO public.country(name, code) VALUES ('Isle of Man', 'IMN');
INSERT INTO public.country(name, code) VALUES ('Israel', 'ISR');
INSERT INTO public.country(name, code) VALUES ('Italy', 'ITA');
INSERT INTO public.country(name, code) VALUES ('Jamaica', 'JAM');
INSERT INTO public.country(name, code) VALUES ('Japan', 'JPN');
INSERT INTO public.country(name, code) VALUES ('Jersey', 'JEY');
INSERT INTO public.country(name, code) VALUES ('Jordan', 'JOR');
INSERT INTO public.country(name, code) VALUES ('Kazakhstan', 'KAZ');
INSERT INTO public.country(name, code) VALUES ('Kenya', 'KEN');
INSERT INTO public.country(name, code) VALUES ('Kiribati', 'KIR');
INSERT INTO public.country(name, code) VALUES ('Korea (North)', 'PRK');
INSERT INTO public.country(name, code) VALUES ('Korea (South)', 'KOR');
INSERT INTO public.country(name, code) VALUES ('Kuwait', 'KWT');
INSERT INTO public.country(name, code) VALUES ('Kyrgyzstan', 'KGZ');
INSERT INTO public.country(name, code) VALUES ('Lao PDR', 'LAO');
INSERT INTO public.country(name, code) VALUES ('Latvia', 'LVA');
INSERT INTO public.country(name, code) VALUES ('Lebanon', 'LBN');
INSERT INTO public.country(name, code) VALUES ('Lesotho', 'LSO');
INSERT INTO public.country(name, code) VALUES ('Liberia', 'LBR');
INSERT INTO public.country(name, code) VALUES ('Libya', 'LBY');
INSERT INTO public.country(name, code) VALUES ('Liechtenstein', 'LIE');
INSERT INTO public.country(name, code) VALUES ('Lithuania', 'LTU');
INSERT INTO public.country(name, code) VALUES ('Luxembourg', 'LUX');
INSERT INTO public.country(name, code) VALUES ('Macedonia, Republic of', 'MKD');
INSERT INTO public.country(name, code) VALUES ('Madagascar', 'MDG');
INSERT INTO public.country(name, code) VALUES ('Malawi', 'MWI');
INSERT INTO public.country(name, code) VALUES ('Malaysia', 'MYS');
INSERT INTO public.country(name, code) VALUES ('Maldives', 'MDV');
INSERT INTO public.country(name, code) VALUES ('Mali', 'MLI');
INSERT INTO public.country(name, code) VALUES ('Malta', 'MLT');
INSERT INTO public.country(name, code) VALUES ('Marshall Islands', 'MHL');
INSERT INTO public.country(name, code) VALUES ('Martinique', 'MTQ');
INSERT INTO public.country(name, code) VALUES ('Mauritania', 'MRT');
INSERT INTO public.country(name, code) VALUES ('Mauritius', 'MUS');
INSERT INTO public.country(name, code) VALUES ('Mayotte', 'MYT');
INSERT INTO public.country(name, code) VALUES ('Mexico', 'MEX');
INSERT INTO public.country(name, code) VALUES ('Micronesia, Federated States of', 'FSM');
INSERT INTO public.country(name, code) VALUES ('Moldova', 'MDA');
INSERT INTO public.country(name, code) VALUES ('Monaco', 'MCO');
INSERT INTO public.country(name, code) VALUES ('Mongolia', 'MNG');
INSERT INTO public.country(name, code) VALUES ('Montenegro', 'MNE');
INSERT INTO public.country(name, code) VALUES ('Montserrat', 'MSR');
INSERT INTO public.country(name, code) VALUES ('Morocco', 'MAR');
INSERT INTO public.country(name, code) VALUES ('Mozambique', 'MOZ');
INSERT INTO public.country(name, code) VALUES ('Myanmar', 'MMR');
INSERT INTO public.country(name, code) VALUES ('Namibia', 'NAM');
INSERT INTO public.country(name, code) VALUES ('Nauru', 'NRU');
INSERT INTO public.country(name, code) VALUES ('Nepal', 'NPL');
INSERT INTO public.country(name, code) VALUES ('Netherlands', 'NLD');
INSERT INTO public.country(name, code) VALUES ('Netherlands Antilles', 'ANT');
INSERT INTO public.country(name, code) VALUES ('New Caledonia', 'NCL');
INSERT INTO public.country(name, code) VALUES ('New Zealand', 'NZL');
INSERT INTO public.country(name, code) VALUES ('Nicaragua', 'NIC');
INSERT INTO public.country(name, code) VALUES ('Niger', 'NER');
INSERT INTO public.country(name, code) VALUES ('Nigeria', 'NGA');
INSERT INTO public.country(name, code) VALUES ('Niue', 'NIU');
INSERT INTO public.country(name, code) VALUES ('Norfolk Island', 'NFK');
INSERT INTO public.country(name, code) VALUES ('Northern Mariana Islands', 'MNP');
INSERT INTO public.country(name, code) VALUES ('Norway', 'NOR');
INSERT INTO public.country(name, code) VALUES ('Oman', 'OMN');
INSERT INTO public.country(name, code) VALUES ('Pakistan', 'PAK');
INSERT INTO public.country(name, code) VALUES ('Palau', 'PLW');
INSERT INTO public.country(name, code) VALUES ('Palestinian Territory', 'PSE');
INSERT INTO public.country(name, code) VALUES ('Panama', 'PAN');
INSERT INTO public.country(name, code) VALUES ('Papua New Guinea', 'PNG');
INSERT INTO public.country(name, code) VALUES ('Paraguay', 'PRY');
INSERT INTO public.country(name, code) VALUES ('Peru', 'PER');
INSERT INTO public.country(name, code) VALUES ('Philippines', 'PHL');
INSERT INTO public.country(name, code) VALUES ('Pitcairn', 'PCN');
INSERT INTO public.country(name, code) VALUES ('Poland', 'POL');
INSERT INTO public.country(name, code) VALUES ('Portugal', 'PRT');
INSERT INTO public.country(name, code) VALUES ('Puerto Rico', 'PRI');
INSERT INTO public.country(name, code) VALUES ('Qatar', 'QAT');
INSERT INTO public.country(name, code) VALUES ('Réunion', 'REU');
INSERT INTO public.country(name, code) VALUES ('Romania', 'ROU');
INSERT INTO public.country(name, code) VALUES ('Russian Federation', 'RUS');
INSERT INTO public.country(name, code) VALUES ('Rwanda', 'RWA');
INSERT INTO public.country(name, code) VALUES ('Saint-Barthélemy', 'BLM');
INSERT INTO public.country(name, code) VALUES ('Saint Helena', 'SHN');
INSERT INTO public.country(name, code) VALUES ('Saint Kitts and Nevis', 'KNA');
INSERT INTO public.country(name, code) VALUES ('Saint Lucia', 'LCA');
INSERT INTO public.country(name, code) VALUES ('Saint-Martin (French part)', 'MAF');
INSERT INTO public.country(name, code) VALUES ('Saint Pierre and Miquelon', 'SPM');
INSERT INTO public.country(name, code) VALUES ('Saint Vincent and Grenadines', 'VCT');
INSERT INTO public.country(name, code) VALUES ('Samoa', 'WSM');
INSERT INTO public.country(name, code) VALUES ('San Marino', 'SMR');
INSERT INTO public.country(name, code) VALUES ('Sao Tome and Principe', 'STP');
INSERT INTO public.country(name, code) VALUES ('Saudi Arabia', 'SAU');
INSERT INTO public.country(name, code) VALUES ('Senegal', 'SEN');
INSERT INTO public.country(name, code) VALUES ('Serbia', 'SRB');
INSERT INTO public.country(name, code) VALUES ('Seychelles', 'SYC');
INSERT INTO public.country(name, code) VALUES ('Sierra Leone', 'SLE');
INSERT INTO public.country(name, code) VALUES ('Singapore', 'SGP');
INSERT INTO public.country(name, code) VALUES ('Slovakia', 'SVK');
INSERT INTO public.country(name, code) VALUES ('Slovenia', 'SVN');
INSERT INTO public.country(name, code) VALUES ('Solomon Islands', 'SLB');
INSERT INTO public.country(name, code) VALUES ('Somalia', 'SOM');
INSERT INTO public.country(name, code) VALUES ('South Africa', 'ZAF');
INSERT INTO public.country(name, code) VALUES ('South Georgia and the South Sandwich Islands', 'SGS');
INSERT INTO public.country(name, code) VALUES ('South Sudan', 'SSD');
INSERT INTO public.country(name, code) VALUES ('Spain', 'ESP');
INSERT INTO public.country(name, code) VALUES ('Sri Lanka', 'LKA');
INSERT INTO public.country(name, code) VALUES ('Sudan', 'SDN');
INSERT INTO public.country(name, code) VALUES ('Suriname', 'SUR');
INSERT INTO public.country(name, code) VALUES ('Svalbard and Jan Mayen Islands', 'SJM');
INSERT INTO public.country(name, code) VALUES ('Swaziland', 'SWZ');
INSERT INTO public.country(name, code) VALUES ('Sweden', 'SWE');
INSERT INTO public.country(name, code) VALUES ('Switzerland', 'CHE');
INSERT INTO public.country(name, code) VALUES ('Syrian Arab Republic (Syria)', 'SYR');
INSERT INTO public.country(name, code) VALUES ('Taiwan, Republic of China', 'TWN');
INSERT INTO public.country(name, code) VALUES ('Tajikistan', 'TJK');
INSERT INTO public.country(name, code) VALUES ('Tanzania, United Republic of', 'TZA');
INSERT INTO public.country(name, code) VALUES ('Thailand', 'THA');
INSERT INTO public.country(name, code) VALUES ('Timor-Leste', 'TLS');
INSERT INTO public.country(name, code) VALUES ('Togo', 'TGO');
INSERT INTO public.country(name, code) VALUES ('Tokelau', 'TKL');
INSERT INTO public.country(name, code) VALUES ('Tonga', 'TON');
INSERT INTO public.country(name, code) VALUES ('Trinidad and Tobago', 'TTO');
INSERT INTO public.country(name, code) VALUES ('Tunisia', 'TUN');
INSERT INTO public.country(name, code) VALUES ('Turkey', 'TUR');
INSERT INTO public.country(name, code) VALUES ('Turkmenistan', 'TKM');
INSERT INTO public.country(name, code) VALUES ('Turks and Caicos Islands', 'TCA');
INSERT INTO public.country(name, code) VALUES ('Tuvalu', 'TUV');
INSERT INTO public.country(name, code) VALUES ('Uganda', 'UGA');
INSERT INTO public.country(name, code) VALUES ('Ukraine', 'UKR');
INSERT INTO public.country(name, code) VALUES ('United Arab Emirates', 'ARE');
INSERT INTO public.country(name, code) VALUES ('United Kingdom', 'GBR');
INSERT INTO public.country(name, code) VALUES ('United States of America', 'USA');
INSERT INTO public.country(name, code) VALUES ('US Minor Outlying Islands', 'UMI');
INSERT INTO public.country(name, code) VALUES ('Uruguay', 'URY');
INSERT INTO public.country(name, code) VALUES ('Uzbekistan', 'UZB');
INSERT INTO public.country(name, code) VALUES ('Vanuatu', 'VUT');
INSERT INTO public.country(name, code) VALUES ('Venezuela (Bolivarian Republic)', 'VEN');
INSERT INTO public.country(name, code) VALUES ('Viet Nam', 'VNM');
INSERT INTO public.country(name, code) VALUES ('Virgin Islands, US', 'VIR');
INSERT INTO public.country(name, code) VALUES ('Wallis and Futuna Islands', 'WLF');
INSERT INTO public.country(name, code) VALUES ('Western Sahara', 'ESH');
INSERT INTO public.country(name, code) VALUES ('Yemen', 'YEM');
INSERT INTO public.country(name, code) VALUES ('Zambia', 'ZMB');
INSERT INTO public.country(name, code) VALUES ('Zimbabwe', 'ZWE');