-- NSI

-- vpn server statuses
INSERT INTO public.vpnserver_status(id, code, description) VALUES(0, 'unknown', 'Unknown, for reports only');
INSERT INTO public.vpnserver_status(id, code, description) VALUES(1, 'op', 'Operational');
INSERT INTO public.vpnserver_status(id, code, description) VALUES(2, 'removed', 'Removed of service');
INSERT INTO public.vpnserver_status(id, code, description) VALUES(3, 'maintenance', 'Under Maintenance');
INSERT INTO public.vpnserver_status(id, code, description) VALUES(4, 'op_nnc', 'Operational. No new connections available, preparing for Maintenance');
INSERT INTO public.vpnserver_status(id, code, description) VALUES(5, 'op_test', 'Operational; test mode');
INSERT INTO public.vpnserver_status(id, code, description) VALUES(6, 'removed_test', 'Removed of service; test mode');
INSERT INTO public.vpnserver_status(id, code, description) VALUES(7, 'maintenance_test', 'Under Maintenance; test mode');
INSERT INTO public.vpnserver_status(id, code, description) VALUES(8, 'op_nnc_test', 'Operational. No new connections available, preparing for Maintenance; test mode');

-- vpn types
INSERT INTO public.vpn_type (id, code, description) VALUES (0, 'unknown', 'Unknown, for reports only');
INSERT INTO public.vpn_type (id, code, description) VALUES (1, 'openvpn', 'Standard OpenVPN server');
INSERT INTO public.vpn_type (id, code, description) VALUES (2, 'ikev2', 'IPSec w IKEv2');


INSERT INTO public.country(name, code, str_code) VALUES ('Afghanistan', 004, 'AFG');
INSERT INTO public.country(name, code, str_code) VALUES ('ALA	Aland Islands', 248, 'ALA');
INSERT INTO public.country(name, code, str_code) VALUES ('Albania', 008, 'ALB');
INSERT INTO public.country(name, code, str_code) VALUES ('Algeria', 012, 'DZA');
INSERT INTO public.country(name, code, str_code) VALUES ('American Samoa', 016, 'ASM');
INSERT INTO public.country(name, code, str_code) VALUES ('Andorra', 020, 'AND');
INSERT INTO public.country(name, code, str_code) VALUES ('Angola', 024, 'AGO');
INSERT INTO public.country(name, code, str_code) VALUES ('Anguilla', 660, 'AIA');
INSERT INTO public.country(name, code, str_code) VALUES ('Antarctica', 010, 'ATA');
INSERT INTO public.country(name, code, str_code) VALUES ('Antigua and Barbuda', 028, 'ATG');
INSERT INTO public.country(name, code, str_code) VALUES ('Argentina', 032, 'ARG');
INSERT INTO public.country(name, code, str_code) VALUES ('Armenia', 051, 'ARM');
INSERT INTO public.country(name, code, str_code) VALUES ('Aruba', 533, 'ABW');
INSERT INTO public.country(name, code, str_code) VALUES ('Australia', 036, 'AUS');
INSERT INTO public.country(name, code, str_code) VALUES ('Austria', 040, 'AUT');
INSERT INTO public.country(name, code, str_code) VALUES ('Azerbaijan', 031, 'AZE');
INSERT INTO public.country(name, code, str_code) VALUES ('Bahamas', 044, 'BHS');
INSERT INTO public.country(name, code, str_code) VALUES ('Bahrain', 048, 'BHR');
INSERT INTO public.country(name, code, str_code) VALUES ('Bangladesh', 050, 'BGD');
INSERT INTO public.country(name, code, str_code) VALUES ('Barbados', 052, 'BRB');
INSERT INTO public.country(name, code, str_code) VALUES ('Belarus', 112, 'BLR');
INSERT INTO public.country(name, code, str_code) VALUES ('Belgium', 056, 'BEL');
INSERT INTO public.country(name, code, str_code) VALUES ('Belize', 084, 'BLZ');
INSERT INTO public.country(name, code, str_code) VALUES ('Benin', 204, 'BEN');
INSERT INTO public.country(name, code, str_code) VALUES ('Bermuda', 060, 'BMU');
INSERT INTO public.country(name, code, str_code) VALUES ('Bhutan', 064, 'BTN');
INSERT INTO public.country(name, code, str_code) VALUES ('Bolivia', 068, 'BOL');
INSERT INTO public.country(name, code, str_code) VALUES ('Bosnia and Herzegovina', 535, 'BIH');
INSERT INTO public.country(name, code, str_code) VALUES ('Botswana', 070, 'BWA');
INSERT INTO public.country(name, code, str_code) VALUES ('Bouvet Island', 072, 'BVT');
INSERT INTO public.country(name, code, str_code) VALUES ('Brazil', 074, 'BRA');
INSERT INTO public.country(name, code, str_code) VALUES ('British Virgin Islands', 076, 'VGB');
INSERT INTO public.country(name, code, str_code) VALUES ('British Indian Ocean Territory', 086, 'IOT');
INSERT INTO public.country(name, code, str_code) VALUES ('Brunei Darussalam', 096, 'BRN');
INSERT INTO public.country(name, code, str_code) VALUES ('Bulgaria', 100, 'BGR');
INSERT INTO public.country(name, code, str_code) VALUES ('Burkina Faso', 854, 'BFA');
INSERT INTO public.country(name, code, str_code) VALUES ('Burundi', 108, 'BDI');
INSERT INTO public.country(name, code, str_code) VALUES ('Cambodia', 132, 'KHM');
INSERT INTO public.country(name, code, str_code) VALUES ('Cameroon', 116, 'CMR');
INSERT INTO public.country(name, code, str_code) VALUES ('Canada', 120, 'CAN');
INSERT INTO public.country(name, code, str_code) VALUES ('Cape Verde', 124, 'CPV');
INSERT INTO public.country(name, code, str_code) VALUES ('Cayman Islands', 136, 'CYM');
INSERT INTO public.country(name, code, str_code) VALUES ('Central African Republic', 140, 'CAF');
INSERT INTO public.country(name, code, str_code) VALUES ('Chad', 148, 'TCD');
INSERT INTO public.country(name, code, str_code) VALUES ('Chile', 152, 'CHL');
INSERT INTO public.country(name, code, str_code) VALUES ('China', 156, 'CHN');
INSERT INTO public.country(name, code, str_code) VALUES ('Hong Kong, SAR China', 162, 'HKG');
INSERT INTO public.country(name, code, str_code) VALUES ('Macao, SAR China', 166, 'MAC');
INSERT INTO public.country(name, code, str_code) VALUES ('Christmas Island', 170, 'CXR');
INSERT INTO public.country(name, code, str_code) VALUES ('Cocos (Keeling) Islands', 174, 'CCK');
INSERT INTO public.country(name, code, str_code) VALUES ('Colombia', 178, 'COL');
INSERT INTO public.country(name, code, str_code) VALUES ('Comoros', 180, 'COM');
INSERT INTO public.country(name, code, str_code) VALUES ('Congo (Brazzaville)', 184, 'COG');
INSERT INTO public.country(name, code, str_code) VALUES ('Congo, (Kinshasa)', 188, 'COD');
INSERT INTO public.country(name, code, str_code) VALUES ('Cook Islands', 384, 'COK');
INSERT INTO public.country(name, code, str_code) VALUES ('Costa Rica', 191, 'CRI');
INSERT INTO public.country(name, code, str_code) VALUES ('Côte dIvoire', 192, 'CIV');
INSERT INTO public.country(name, code, str_code) VALUES ('Croatia', 531, 'HRV');
INSERT INTO public.country(name, code, str_code) VALUES ('Cuba', 196, 'CUB');
INSERT INTO public.country(name, code, str_code) VALUES ('Cyprus', 203, 'CYP');
INSERT INTO public.country(name, code, str_code) VALUES ('Czech Republic', 208, 'CZE');
INSERT INTO public.country(name, code, str_code) VALUES ('Denmark', 262, 'DNK');
INSERT INTO public.country(name, code, str_code) VALUES ('Djibouti', 212, 'DJI');
INSERT INTO public.country(name, code, str_code) VALUES ('Dominica', 214, 'DMA');
INSERT INTO public.country(name, code, str_code) VALUES ('Dominican Republic', 218, 'DOM');
INSERT INTO public.country(name, code, str_code) VALUES ('Ecuador', 818, 'ECU');
INSERT INTO public.country(name, code, str_code) VALUES ('Egypt', 222, 'EGY');
INSERT INTO public.country(name, code, str_code) VALUES ('El Salvador', 226, 'SLV');
INSERT INTO public.country(name, code, str_code) VALUES ('Equatorial Guinea', 232, 'GNQ');
INSERT INTO public.country(name, code, str_code) VALUES ('Eritrea', 233, 'ERI');
INSERT INTO public.country(name, code, str_code) VALUES ('Estonia', 231, 'EST');
INSERT INTO public.country(name, code, str_code) VALUES ('Ethiopia', 238, 'ETH');
INSERT INTO public.country(name, code, str_code) VALUES ('Falkland Islands (Malvinas)', 234, 'FLK');
INSERT INTO public.country(name, code, str_code) VALUES ('Faroe Islands', 242, 'FRO');
INSERT INTO public.country(name, code, str_code) VALUES ('Fiji', 246, 'FJI');
INSERT INTO public.country(name, code, str_code) VALUES ('Finland', 250, 'FIN');
INSERT INTO public.country(name, code, str_code) VALUES ('France', 254, 'FRA');
INSERT INTO public.country(name, code, str_code) VALUES ('French Guiana', 258, 'GUF');
INSERT INTO public.country(name, code, str_code) VALUES ('French Polynesia', 260, 'PYF');
INSERT INTO public.country(name, code, str_code) VALUES ('French Southern Territories', 266, 'ATF');
INSERT INTO public.country(name, code, str_code) VALUES ('Gabon', 270, 'GAB');
INSERT INTO public.country(name, code, str_code) VALUES ('Gambia', 268, 'GMB');
INSERT INTO public.country(name, code, str_code) VALUES ('Georgia', 276, 'GEO');
INSERT INTO public.country(name, code, str_code) VALUES ('Germany', 288, 'DEU');
INSERT INTO public.country(name, code, str_code) VALUES ('Ghana', 292, 'GHA');
INSERT INTO public.country(name, code, str_code) VALUES ('Gibraltar', 300, 'GIB');
INSERT INTO public.country(name, code, str_code) VALUES ('Greece', 304, 'GRC');
INSERT INTO public.country(name, code, str_code) VALUES ('Greenland', 308, 'GRL');
INSERT INTO public.country(name, code, str_code) VALUES ('Grenada', 312, 'GRD');
INSERT INTO public.country(name, code, str_code) VALUES ('Guadeloupe', 316, 'GLP');
INSERT INTO public.country(name, code, str_code) VALUES ('Guam', 320, 'GUM');
INSERT INTO public.country(name, code, str_code) VALUES ('Guatemala', 831, 'GTM');
INSERT INTO public.country(name, code, str_code) VALUES ('Guernsey', 324, 'GGY');
INSERT INTO public.country(name, code, str_code) VALUES ('Guinea', 624, 'GIN');
INSERT INTO public.country(name, code, str_code) VALUES ('Guinea-Bissau', 328, 'GNB');
INSERT INTO public.country(name, code, str_code) VALUES ('Guyana', 332, 'GUY');
INSERT INTO public.country(name, code, str_code) VALUES ('Haiti', 334, 'HTI');
INSERT INTO public.country(name, code, str_code) VALUES ('Heard and Mcdonald Islands', 336, 'HMD');
INSERT INTO public.country(name, code, str_code) VALUES ('Holy See (Vatican City State)', 340, 'VAT');
INSERT INTO public.country(name, code, str_code) VALUES ('Honduras', 344, 'HND');
INSERT INTO public.country(name, code, str_code) VALUES ('Hungary', 348, 'HUN');
INSERT INTO public.country(name, code, str_code) VALUES ('Iceland', 352, 'ISL');
INSERT INTO public.country(name, code, str_code) VALUES ('India', 356, 'IND');
INSERT INTO public.country(name, code, str_code) VALUES ('Indonesia', 360, 'IDN');
INSERT INTO public.country(name, code, str_code) VALUES ('Iran, Islamic Republic of', 364, 'IRN');
INSERT INTO public.country(name, code, str_code) VALUES ('Iraq', 368, 'IRQ');
INSERT INTO public.country(name, code, str_code) VALUES ('Ireland', 372, 'IRL');
INSERT INTO public.country(name, code, str_code) VALUES ('Isle of Man', 833, 'IMN');
INSERT INTO public.country(name, code, str_code) VALUES ('Israel', 376, 'ISR');
INSERT INTO public.country(name, code, str_code) VALUES ('Italy', 380, 'ITA');
INSERT INTO public.country(name, code, str_code) VALUES ('Jamaica', 388, 'JAM');
INSERT INTO public.country(name, code, str_code) VALUES ('Japan', 392, 'JPN');
INSERT INTO public.country(name, code, str_code) VALUES ('Jersey', 832, 'JEY');
INSERT INTO public.country(name, code, str_code) VALUES ('Jordan', 400, 'JOR');
INSERT INTO public.country(name, code, str_code) VALUES ('Kazakhstan', 398, 'KAZ');
INSERT INTO public.country(name, code, str_code) VALUES ('Kenya', 404, 'KEN');
INSERT INTO public.country(name, code, str_code) VALUES ('Kiribati', 296, 'KIR');
INSERT INTO public.country(name, code, str_code) VALUES ('Korea (North)', 408, 'PRK');
INSERT INTO public.country(name, code, str_code) VALUES ('Korea (South)', 410, 'KOR');
INSERT INTO public.country(name, code, str_code) VALUES ('Kuwait', 414, 'KWT');
INSERT INTO public.country(name, code, str_code) VALUES ('Kyrgyzstan', 417, 'KGZ');
INSERT INTO public.country(name, code, str_code) VALUES ('Lao PDR', 418, 'LAO');
INSERT INTO public.country(name, code, str_code) VALUES ('Latvia', 428, 'LVA');
INSERT INTO public.country(name, code, str_code) VALUES ('Lebanon', 422, 'LBN');
INSERT INTO public.country(name, code, str_code) VALUES ('Lesotho', 426, 'LSO');
INSERT INTO public.country(name, code, str_code) VALUES ('Liberia', 430, 'LBR');
INSERT INTO public.country(name, code, str_code) VALUES ('Libya', 434, 'LBY');
INSERT INTO public.country(name, code, str_code) VALUES ('Liechtenstein', 438, 'LIE');
INSERT INTO public.country(name, code, str_code) VALUES ('Lithuania', 440, 'LTU');
INSERT INTO public.country(name, code, str_code) VALUES ('Luxembourg', 442, 'LUX');
INSERT INTO public.country(name, code, str_code) VALUES ('Macedonia, Republic of', 446, 'MKD');
INSERT INTO public.country(name, code, str_code) VALUES ('Madagascar', 807, 'MDG');
INSERT INTO public.country(name, code, str_code) VALUES ('Malawi', 450, 'MWI');
INSERT INTO public.country(name, code, str_code) VALUES ('Malaysia', 454, 'MYS');
INSERT INTO public.country(name, code, str_code) VALUES ('Maldives', 458, 'MDV');
INSERT INTO public.country(name, code, str_code) VALUES ('Mali', 462, 'MLI');
INSERT INTO public.country(name, code, str_code) VALUES ('Malta', 466, 'MLT');
INSERT INTO public.country(name, code, str_code) VALUES ('Marshall Islands', 470, 'MHL');
INSERT INTO public.country(name, code, str_code) VALUES ('Martinique', 584, 'MTQ');
INSERT INTO public.country(name, code, str_code) VALUES ('Mauritania', 474, 'MRT');
INSERT INTO public.country(name, code, str_code) VALUES ('Mauritius', 478, 'MUS');
INSERT INTO public.country(name, code, str_code) VALUES ('Mayotte', 480, 'MYT');
INSERT INTO public.country(name, code, str_code) VALUES ('Mexico', 175, 'MEX');
INSERT INTO public.country(name, code, str_code) VALUES ('Micronesia, Federated States of', 484, 'FSM');
INSERT INTO public.country(name, code, str_code) VALUES ('Moldova', 583, 'MDA');
INSERT INTO public.country(name, code, str_code) VALUES ('Monaco', 498, 'MCO');
INSERT INTO public.country(name, code, str_code) VALUES ('Mongolia', 492, 'MNG');
INSERT INTO public.country(name, code, str_code) VALUES ('Montenegro', 496, 'MNE');
INSERT INTO public.country(name, code, str_code) VALUES ('Montserrat', 499, 'MSR');
INSERT INTO public.country(name, code, str_code) VALUES ('Morocco', 500, 'MAR');
INSERT INTO public.country(name, code, str_code) VALUES ('Mozambique', 504, 'MOZ');
INSERT INTO public.country(name, code, str_code) VALUES ('Myanmar', 508, 'MMR');
INSERT INTO public.country(name, code, str_code) VALUES ('Namibia', 104, 'NAM');
INSERT INTO public.country(name, code, str_code) VALUES ('Nauru', 516, 'NRU');
INSERT INTO public.country(name, code, str_code) VALUES ('Nepal', 520, 'NPL');
INSERT INTO public.country(name, code, str_code) VALUES ('Netherlands', 524, 'NLD');
INSERT INTO public.country(name, code, str_code) VALUES ('Netherlands Antilles', 528, 'ANT');
INSERT INTO public.country(name, code, str_code) VALUES ('New Caledonia', 540, 'NCL');
INSERT INTO public.country(name, code, str_code) VALUES ('New Zealand', 554, 'NZL');
INSERT INTO public.country(name, code, str_code) VALUES ('Nicaragua', 558, 'NIC');
INSERT INTO public.country(name, code, str_code) VALUES ('Niger', 562, 'NER');
INSERT INTO public.country(name, code, str_code) VALUES ('Nigeria', 566, 'NGA');
INSERT INTO public.country(name, code, str_code) VALUES ('Niue', 570, 'NIU');
INSERT INTO public.country(name, code, str_code) VALUES ('Norfolk Island', 574, 'NFK');
INSERT INTO public.country(name, code, str_code) VALUES ('Northern Mariana Islands', 580, 'MNP');
INSERT INTO public.country(name, code, str_code) VALUES ('Norway', 578, 'NOR');
INSERT INTO public.country(name, code, str_code) VALUES ('Oman', 512, 'OMN');
INSERT INTO public.country(name, code, str_code) VALUES ('Pakistan', 586, 'PAK');
INSERT INTO public.country(name, code, str_code) VALUES ('Palau', 585, 'PLW');
INSERT INTO public.country(name, code, str_code) VALUES ('Palestinian Territory', 275, 'PSE');
INSERT INTO public.country(name, code, str_code) VALUES ('Panama', 591, 'PAN');
INSERT INTO public.country(name, code, str_code) VALUES ('Papua New Guinea', 598, 'PNG');
INSERT INTO public.country(name, code, str_code) VALUES ('Paraguay', 600, 'PRY');
INSERT INTO public.country(name, code, str_code) VALUES ('Peru', 604, 'PER');
INSERT INTO public.country(name, code, str_code) VALUES ('Philippines', 608, 'PHL');
INSERT INTO public.country(name, code, str_code) VALUES ('Pitcairn', 612, 'PCN');
INSERT INTO public.country(name, code, str_code) VALUES ('Poland', 616, 'POL');
INSERT INTO public.country(name, code, str_code) VALUES ('Portugal', 620, 'PRT');
INSERT INTO public.country(name, code, str_code) VALUES ('Puerto Rico', 630, 'PRI');
INSERT INTO public.country(name, code, str_code) VALUES ('Qatar', 634, 'QAT');
INSERT INTO public.country(name, code, str_code) VALUES ('Réunion', 638, 'REU');
INSERT INTO public.country(name, code, str_code) VALUES ('Romania', 642, 'ROU');
INSERT INTO public.country(name, code, str_code) VALUES ('Russian Federation', 643, 'RUS');
INSERT INTO public.country(name, code, str_code) VALUES ('Rwanda', 646, 'RWA');
INSERT INTO public.country(name, code, str_code) VALUES ('Saint-Barthélemy', 652, 'BLM');
INSERT INTO public.country(name, code, str_code) VALUES ('Saint Helena', 654, 'SHN');
INSERT INTO public.country(name, code, str_code) VALUES ('Saint Kitts and Nevis', 659, 'KNA');
INSERT INTO public.country(name, code, str_code) VALUES ('Saint Lucia', 662, 'LCA');
INSERT INTO public.country(name, code, str_code) VALUES ('Saint-Martin (French part)', 663, 'MAF');
INSERT INTO public.country(name, code, str_code) VALUES ('Saint Pierre and Miquelon', 666, 'SPM');
INSERT INTO public.country(name, code, str_code) VALUES ('Saint Vincent and Grenadines', 670, 'VCT');
INSERT INTO public.country(name, code, str_code) VALUES ('Samoa', 882, 'WSM');
INSERT INTO public.country(name, code, str_code) VALUES ('San Marino', 674, 'SMR');
INSERT INTO public.country(name, code, str_code) VALUES ('Sao Tome and Principe', 678, 'STP');
INSERT INTO public.country(name, code, str_code) VALUES ('Saudi Arabia', 682, 'SAU');
INSERT INTO public.country(name, code, str_code) VALUES ('Senegal', 686, 'SEN');
INSERT INTO public.country(name, code, str_code) VALUES ('Serbia', 688, 'SRB');
INSERT INTO public.country(name, code, str_code) VALUES ('Seychelles', 690, 'SYC');
INSERT INTO public.country(name, code, str_code) VALUES ('Sierra Leone', 694, 'SLE');
INSERT INTO public.country(name, code, str_code) VALUES ('Singapore', 702, 'SGP');
INSERT INTO public.country(name, code, str_code) VALUES ('Slovakia', 534, 'SVK');
INSERT INTO public.country(name, code, str_code) VALUES ('Slovenia', 703, 'SVN');
INSERT INTO public.country(name, code, str_code) VALUES ('Solomon Islands', 705, 'SLB');
INSERT INTO public.country(name, code, str_code) VALUES ('Somalia', 090, 'SOM');
INSERT INTO public.country(name, code, str_code) VALUES ('South Africa', 706, 'ZAF');
INSERT INTO public.country(name, code, str_code) VALUES ('South Georgia and the South Sandwich Islands', 710, 'SGS');
INSERT INTO public.country(name, code, str_code) VALUES ('South Sudan', 239, 'SSD');
INSERT INTO public.country(name, code, str_code) VALUES ('Spain', 728, 'ESP');
INSERT INTO public.country(name, code, str_code) VALUES ('Sri Lanka', 724, 'LKA');
INSERT INTO public.country(name, code, str_code) VALUES ('Sudan', 144, 'SDN');
INSERT INTO public.country(name, code, str_code) VALUES ('Suriname', 729, 'SUR');
INSERT INTO public.country(name, code, str_code) VALUES ('Svalbard and Jan Mayen Islands', 740, 'SJM');
INSERT INTO public.country(name, code, str_code) VALUES ('Swaziland', 744, 'SWZ');
INSERT INTO public.country(name, code, str_code) VALUES ('Sweden', 748, 'SWE');
INSERT INTO public.country(name, code, str_code) VALUES ('Switzerland', 752, 'CHE');
INSERT INTO public.country(name, code, str_code) VALUES ('Syrian Arab Republic (Syria)', 756, 'SYR');
INSERT INTO public.country(name, code, str_code) VALUES ('Taiwan, Republic of China', 760, 'TWN');
INSERT INTO public.country(name, code, str_code) VALUES ('Tajikistan', 158, 'TJK');
INSERT INTO public.country(name, code, str_code) VALUES ('Tanzania, United Republic of', 762, 'TZA');
INSERT INTO public.country(name, code, str_code) VALUES ('Thailand', 834, 'THA');
INSERT INTO public.country(name, code, str_code) VALUES ('Timor-Leste', 764, 'TLS');
INSERT INTO public.country(name, code, str_code) VALUES ('Togo', 626, 'TGO');
INSERT INTO public.country(name, code, str_code) VALUES ('Tokelau', 768, 'TKL');
INSERT INTO public.country(name, code, str_code) VALUES ('Tonga', 772, 'TON');
INSERT INTO public.country(name, code, str_code) VALUES ('Trinidad and Tobago', 776, 'TTO');
INSERT INTO public.country(name, code, str_code) VALUES ('Tunisia', 780, 'TUN');
INSERT INTO public.country(name, code, str_code) VALUES ('Turkey', 788, 'TUR');
INSERT INTO public.country(name, code, str_code) VALUES ('Turkmenistan', 792, 'TKM');
INSERT INTO public.country(name, code, str_code) VALUES ('Turks and Caicos Islands', 795, 'TCA');
INSERT INTO public.country(name, code, str_code) VALUES ('Tuvalu', 796, 'TUV');
INSERT INTO public.country(name, code, str_code) VALUES ('Uganda', 798, 'UGA');
INSERT INTO public.country(name, code, str_code) VALUES ('Ukraine', 800, 'UKR');
INSERT INTO public.country(name, code, str_code) VALUES ('United Arab Emirates', 804, 'ARE');
INSERT INTO public.country(name, code, str_code) VALUES ('United Kingdom', 784, 'GBR');
INSERT INTO public.country(name, code, str_code) VALUES ('United States of America', 826, 'USA');
INSERT INTO public.country(name, code, str_code) VALUES ('US Minor Outlying Islands', 840, 'UMI');
INSERT INTO public.country(name, code, str_code) VALUES ('Uruguay', 581, 'URY');
INSERT INTO public.country(name, code, str_code) VALUES ('Uzbekistan', 858, 'UZB');
INSERT INTO public.country(name, code, str_code) VALUES ('Vanuatu', 860, 'VUT');
INSERT INTO public.country(name, code, str_code) VALUES ('Venezuela (Bolivarian Republic)', 548, 'VEN');
INSERT INTO public.country(name, code, str_code) VALUES ('Viet Nam', 862, 'VNM');
INSERT INTO public.country(name, code, str_code) VALUES ('Virgin Islands, US', 704, 'VIR');
INSERT INTO public.country(name, code, str_code) VALUES ('Wallis and Futuna Islands', 092, 'WLF');
INSERT INTO public.country(name, code, str_code) VALUES ('Western Sahara', 850, 'ESH');
INSERT INTO public.country(name, code, str_code) VALUES ('Yemen', 876, 'YEM');
INSERT INTO public.country(name, code, str_code) VALUES ('Zambia', 732, 'ZMB');
INSERT INTO public.country(name, code, str_code) VALUES ('Zimbabwe', 887, 'ZWE');


INSERT INTO public.city (id, name, created_date) VALUES (1, 'New York', '2018-05-23 12:26:01.601516');
INSERT INTO public.city (id, name, created_date) VALUES (2, 'Moscow', '2018-05-23 12:26:26.319747');

-- geo position
INSERT INTO public.geo_position (id, latitude, longitude, country_code, state_code, city_id, region_common, region_dvd, region_xbox360, region_xboxone, region_playstation3, region_playstation4, region_nintendo, created_date) VALUES (1, 55.108, 54.039, 826, null, 1, 0, 0, 0, 0, 0, 0, 0, '2018-05-22 13:17:42.947280');

-- vpn server
INSERT INTO public.vpnserver (uuid, version, state_version, type_id, status_id, bandwidth, load, geo_position_id, created_date) VALUES ('c872e7f0-76d6-4a4e-826e-c56a7c05958a', 1, 1, 1, 1, 0, 0, 1, '2018-05-22 13:18:14.041628');

-- vpn server configuration
INSERT INTO public.vpnserver_configuration (uuid, user_uuid, server_uuid, file_path, created_date) VALUES ('8f525324-f752-4135-bab7-38e0f1ff96f9', 'c872e7f0-76d6-4a4e-826e-c56a7c05958a', 'c872e7f0-76d6-4a4e-826e-c56a7c05958a', '/file/path', '2018-05-22 13:25:29.392613');